language: php
php:
    - '7.2'

install:
  - travis_retry composer install
  - travis_retry composer require --dev php-coveralls/php-coveralls

script:
  - composer test
  - composer test-coverage

after_script:
- travis_retry php vendor/bin/php-coveralls -v
- travis_retry composer upload-coverage
